version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test